### PR TITLE
S3 receiver

### PR DESCRIPTION
**Pull request by destrex271**
References - 
 - #34

### CODE REVIEW

**Comment by pashagolub** [comment]
Looks like abandoned one? Should we drop it and focus on other things?

**Comment by destrex271** [comment]
Its WIP rn,  sort of like an add on. Currently working on imporving the llm one

**Comment by pashagolub** [comment]
Converted to draft just to know it's WIP

**Review by pashagolub — APPROVED** [review]
LGTM

**Comment by destrex271** [comment]
Cool merging this

**Pull request merged**
