### PR TITLE
Refactor/project restructure

### PR DESCRIPTION
**Pull request by destrex271**
References #14 

Please review @pashagolub

### CODE REVIEW

**Comment by pashagolub** [comment]
Cool! You're rocket fast! Will do tomorrow :-) THanks

**Review by pashagolub — CHANGES_REQUESTED** [review]
`module pgwatch3_rpc_receiver` must be `module github.com/destrex271/pgwatch3_rpc_receiver`

**Review by pashagolub — CHANGES_REQUESTED** [review]
```
import(
  . "pgwatch3_rpc_receiver/sinks"`
)
```
 must be
```
import(
  "github.com/destrex271/pgwatch3_rpc_receiver/sinks"`
)
```

**Review by pashagolub — CHANGES_REQUESTED** [review]
Remove from README.md:

>In the second terminal switch to the directory `dummy_client/src` and

**Review by pashagolub — CHANGES_REQUESTED** [review]
In README.md update how to start the receiver:

```bash
# For Text sink
$ go run ./cmd/text_receiver --port:5050
# For CSV sink
$ go run ./cmd/csv_receiver --port:5050
# For Parquet sink
$ go run ./cmd/parquet_receiver --port:5050
```

Please, add necessary options.

**Comment by destrex271** [comment]
All set! Merging this PR

**Comment by pashagolub** [comment]
Please, do not merge pull request:
1. Until everything is requested is implemented
2. Until I reviewed and accepted
3. Until you check everything

This PR is certainly not finished and just corrupted the main branch beyond the imagination.

**Pull request merged**
